<Project>
  <ItemGroup Condition="$([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('ios'))">
    <DotNativeNativeSource Include="$(MSBuildThisFileDirectory)../Platform/iOS/**/*.swift" />
    <DotNativePluginEntry Include="DotNativeWheelDatePickerPlugin" />
  </ItemGroup>
  <ItemGroup Condition="$([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('android-'))">
    <DotNativeNativeSource Include="$(MSBuildThisFileDirectory)../Platform/Android/**/*.kt" />
    <DotNativePluginEntry Include="DotNativeWheelDatePickerPlugin" />
  </ItemGroup>
  <ItemGroup Condition="$([System.String]::Copy('$(RuntimeIdentifier)').StartsWith('linux-bionic-'))">
    <DotNativeNativeSource Include="$(MSBuildThisFileDirectory)../Platform/Android/**/*.kt" />
    <DotNativePluginEntry Include="DotNativeWheelDatePickerPlugin" />
  </ItemGroup>
</Project>
